CREATE TABLE IF NOT EXISTS `poe`.`events`
(
    `id`    INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name`  VARCHAR(64) NOT NULL UNIQUE,
    `active` BOOLEAN NOT NULL DEFAULT 0,
    `league_id` INT UNSIGNED NOT NULL
);